# This policy verifies the installation of the official & supported version of
# the Compliance Operator on the managed clusters.
#
# If set to "enforce" it'll install the operator.
#
# Note that OpenShift 4.18 is required.
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-storage-cluster
  namespace: {{ .Values.policy_namespace }}
  annotations:
    policy.open-cluster-management.io/standards: NIST SP 800-53
    policy.open-cluster-management.io/categories: CA Security Assessment and Authorization
    policy.open-cluster-management.io/controls: CA-2 Security Assessments, CA-7 Continuous Monitoring
spec:
  dependencies:
    - name: policy-odf-operator-install
      namespace: {{ .Values.policy_namespace }}
      apiVersion: policy.open-cluster-management.io/v1
      compliance: Compliant
      kind: Policy
    - name: policy-storage-nodes-test
      namespace: {{ .Values.policy_namespace }}
      apiVersion: policy.open-cluster-management.io/v1
      compliance: Compliant
      kind: Policy
  disabled: false
  policy-templates:
  # Adding Toleration for csi plugin to run on all nodes.
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: rook-ceph-operator-config
        spec:
          remediationAction: enforce
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                kind: ConfigMap
                apiVersion: v1
                metadata:
                  name: rook-ceph-operator-config
                  namespace: {{ .Values.odf.namespace }}
                data:
                  CSI_LOG_LEVEL: '5'
                  CSI_PLUGIN_TOLERATIONS: |2-

                    - operator: Exists
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: storage-cluster-install
        spec:
          remediationAction: enforce
          severity: high
          object-templates-raw: |
            - complianceType: musthave
              objectDefinition:
                apiVersion: ocs.openshift.io/v1
                kind: StorageCluster
                metadata:
                  name: ocs-storagecluster
                  namespace: {{ .Values.odf.namespace }}
                spec:
                  storageDeviceSets:
                    - config: {}
                      count: '{{ "{{hub" }} index .ManagedClusterLabels "autoshift.io/odf-ocs-storage-count" | default "{{ .Values.odf.ocsStorageCount }}" | toInt {{ "hub}}" }}'
                      dataPVCTemplate:
                        metadata: {}
                        spec:
                          accessModes:
                            - ReadWriteOnce
                          {{ "{{hub-" }} if eq (index .ManagedClusterLabels "autoshift.io/local-storage" | default "") "true" {{ "hub}}" }}
                          resources:
                            requests:
                              storage: '1' # will use whole PV from local storage
                          storageClassName: nvme-storageclass
                          {{ "{{hub-" }} else {{ "hub}}" }}
                          resources:
                            requests:
                              storage: '{{ "{{hub" }} index .ManagedClusterLabels "autoshift.io/odf-ocs-storage-size" | default "{{ .Values.odf.ocsStorageSize}}" {{ "hub}}" }}'
                          storageClassName: '{{ "{{hub" }} index .ManagedClusterLabels "autoshift.io/odf-ocs-storage-class-name" | default "{{ .Values.odf.ocsStorageClassName }}" {{ "hub}}" }}'
                          {{ "{{hub-" }} end {{ "hub}}" }}
                          volumeMode: Block
                        status: {}
                      name: ocs-deviceset
                      placement: {}
                      preparePlacement: {}
                      replica: '{{ "{{hub" }} index .ManagedClusterLabels "autoshift.io/odf-ocs-storage-replicas" | default "{{ .Values.odf.ocsStorageReplicas }}" | toInt {{ "hub}}" }}'
                      resources: {}
                  encryption:
                    clusterWide: true
                    enable: true
                    keyRotation:
                      schedule: '@weekly'
                    kms: {}
                  monDataDirHostPath: '/var/lib/rook'
                  managedResources:
                    cephObjectStoreUsers: {}
                    cephCluster: {}
                    cephBlockPools:
                      defaultStorageClass: true
                    cephNonResilientPools:
                      count: 1
                      resources: {}
                      volumeClaimTemplate:
                        metadata: {}
                        spec:
                          resources: {}
                        status: {}
                    cephObjectStores: {}
                    cephFilesystems:
                      dataPoolSpec:
                        application: ''
                        erasureCoded:
                          codingChunks: 0
                          dataChunks: 0
                        mirroring: {}
                        quotas: {}
                        replicated:
                          size: 0
                        statusCheck:
                          mirror: {}
                    cephRBDMirror:
                      daemonCount: 1
                    cephToolbox: {}
                    cephDashboard: {}
                    cephConfig: {}
                  arbiter: {}
                  multiCloudGateway:
                    reconcileStrategy: manage
                  network:
                    connections:
                      encryption:
                        enabled: true
                    multiClusterService: {}
                    selectors: {}
                {{ "{{hub-" }} if index .ManagedClusterLabels "autoshift.io/odf-ocs-flexible-scaling" {{ "hub}}" }}
                  flexibleScaling: {{ "{{hub" }} index .ManagedClusterLabels "autoshift.io/odf-ocs-flexible-scaling" {{ "hub}}" }}
                {{ "{{hub-" }} else if (and
                  (eq (index .ManagedClusterLabels "autoshift.io/storage-nodes-provider") "baremetal")
                  (ne (sub (index .ManagedClusterLabels "autoshift.io/storage-nodes" | default "0" | toInt)
                    (mul 3 (div (index .ManagedClusterLabels "autoshift.io/storage-nodes" | default "0" | toInt) 3))) 0)) {{ "hub}}" }}
                  flexibleScaling: true
                {{ "{{hub- end hub}}" }}
                  nodeTopologies: {}
                  externalStorage: {}
                  resourceProfile: '{{ "{{hub" }} index .ManagedClusterLabels "autoshift.io/odf-resource-profile" | default "{{ .Values.odf.resourceProfile }}" {{ "hub}}" }}'
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: placement-policy-storage-cluster
  namespace: {{ .Values.policy_namespace }}
spec:
  clusterSets:
  {{- range $clusterSet, $value := $.Values.managedClusterSets }}
    - {{ $clusterSet }}
  {{- end }}
  {{- range $clusterSet, $value := $.Values.hubClusterSets }}
    - {{ $clusterSet }}
  {{- end }}
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: 'autoshift.io/odf'
              operator: In
              values:
              - 'true'
            - key: 'autoshift.io/odf-multi-cloud-gateway'
              operator: NotIn
              values:
              - 'standalone'
  tolerations:
    - key: cluster.open-cluster-management.io/unreachable
      operator: Exists
    - key: cluster.open-cluster-management.io/unavailable
      operator: Exists
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: placement-policy-storage-cluster
  namespace: {{ .Values.policy_namespace }}
placementRef:
  name: placement-policy-storage-cluster
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
subjects:
  - name: policy-storage-cluster
    apiGroup: policy.open-cluster-management.io
    kind: Policy
