# This policy verifies the installation of the official & supported version of
# the Cluster Observability Operator on the managed clusters.
#
# Note that OpenShift 4.18 is required.
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-cluster-observ-op-install
  namespace: {{ .Values.policy_namespace }}
  annotations:
    policy.open-cluster-management.io/standards: NIST SP 800-53
    policy.open-cluster-management.io/categories: CA Security Assessment and Authorization
    policy.open-cluster-management.io/controls: CA-2 Security Assessments, CA-7 Continuous Monitoring
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: coo-operator-ns
        spec:
          remediationAction: enforce
          severity: high
          object-templates-raw: |
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Namespace
                metadata:
                  name: {{ .Values.coo.namespace }}
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1beta1
        kind: OperatorPolicy
        metadata:
          name: install-operator-coo
        spec:
          remediationAction: enforce
          severity: high
          complianceType: musthave
          operatorGroup:
            name: {{ .Values.coo.namespace }}
            namespace: {{ .Values.coo.namespace }}
          subscription:
            startingCSV: '{{ "{{hub" }} index .ManagedClusterLabels "autoshift.io/coo-version" | default "" {{ "hub}}" }}'
            name: '{{ "{{hub" }} index .ManagedClusterLabels "autoshift.io/coo-subscription-name" | default "{{ .Values.coo.name }}" {{ "hub}}" }}'
            namespace: {{ .Values.coo.namespace }}
            source: '{{ "{{hub" }} index .ManagedClusterLabels "autoshift.io/coo-source" | default "{{ .Values.coo.source }}" {{ "hub}}" }}'
            sourceNamespace: '{{ "{{hub" }} index .ManagedClusterLabels "autoshift.io/coo-source-namespace" | default "{{ .Values.coo.sourceNamespace }}" {{ "hub}}" }}'
            channel: '{{ "{{hub" }} index .ManagedClusterLabels "autoshift.io/coo-channel" | default "{{ .Values.coo.channel }}" {{ "hub}}" }}'
          # Upgrade approval for subscription will be set based on if version is set not this flag
          # If version is set install plan is set to manual and only the version specified will be installed
          upgradeApproval: Automatic
          versions:
            - '{{ "{{hub" }} index .ManagedClusterLabels "autoshift.io/coo-version" | default "" {{ "hub}}" }}'
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: openshift-coo-status
        spec:
          remediationAction: inform
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1alpha1
                kind: ClusterServiceVersion
                metadata:
                  namespace: {{ .Values.coo.namespace }}
                spec:
                  displayName: Cluster Observability Operator
                status:
                  phase: Succeeded # check the csv status to determine if operator is running or not
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: placement-policy-cluster-observ-op-install
  namespace: {{ .Values.policy_namespace }}
spec:
  clusterSets:
  {{- range $clusterSet, $value := $.Values.managedClusterSets }}
    - {{ $clusterSet }}
  {{- end }}
  {{- range $clusterSet, $value := $.Values.hubClusterSets }}
    - {{ $clusterSet }}
  {{- end }}
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: 'autoshift.io/coo'
              operator: In
              values:
              - 'true'
  tolerations:
    - key: cluster.open-cluster-management.io/unreachable
      operator: Exists
    - key: cluster.open-cluster-management.io/unavailable
      operator: Exists
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: placement-policy-cluster-observ-op-install
  namespace: {{ .Values.policy_namespace }}
placementRef:
  name: placement-policy-cluster-observ-op-install
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
subjects:
  - name: policy-cluster-observ-op-install
    apiGroup: policy.open-cluster-management.io
    kind: Policy
