# Default values for developer-hub.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
policy_namespace: open-cluster-policies
developerHub:
    name: rhdh
    namespace: rhdh-operator
    channel: fast
    source: redhat-operators
    sourceNamespace: openshift-marketplace
# hubClusterSets:
#   hub:
#     labels:
#       test1: 'test'
# managedClusterSets:
#   managed:
#     labels:
#       test4: 'test'

### AutoShift Labels Documentation
# The following labels can be set at the cluster or clusterset level to configure this policy:
#
# Enable/Disable:
# dev-hub<bool>: 'true' or 'false' - Enable Red Hat Developer Hub (default: 'false')
#
# Configuration:
# dev-hub-channel<String>: Operator channel (default: 'fast')
# dev-hub-version<String>: Specific operator version (CSV) to install (optional)
# dev-hub-source<String>: Operator catalog source (default: 'redhat-operators')
# dev-hub-source-namespace<String>: Catalog namespace (default: 'openshift-marketplace')
#
# Note: Red Hat Developer Hub provides a developer portal and platform
# Built on Backstage, it offers software templates, documentation, and developer tools
#
# Examples:
# autoshift.io/dev-hub: 'true'
# autoshift.io/dev-hub-channel: 'fast'
# autoshift.io/dev-hub-version: 'rhdh.vx.x.x'