# Default values for cluster-observability.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
policy_namespace: open-cluster-policies
coo:
    name: cluster-observability-operator
    namespace: openshift-cluster-observability-operator
    channel: stable
    source: redhat-operators
    sourceNamespace: openshift-marketplace
# hubClusterSets:
#   hub:
#     labels:
#       test1: 'test'
# managedClusterSets:
#   managed:
#     labels:
#       test4: 'test'

### AutoShift Labels Documentation
# The following labels can be set at the cluster or clusterset level to configure this policy:
#
# Enable/Disable:
# coo<bool>: 'true' or 'false' - Enable Cluster Observability Operator (default: 'false')
#
# Configuration:
# coo-channel<String>: Operator channel (default: 'stable')
# coo-version<String>: Specific operator version (CSV) to install (optional)
# coo-source<String>: Operator catalog source (default: 'redhat-operators')
# coo-source-namespace<String>: Catalog namespace (default: 'openshift-marketplace')
#
# Note: Cluster Observability Operator provides UI observability for clusters
# Integrates with OpenShift console for cluster monitoring and alerting
#
# Examples:
# autoshift.io/coo: 'true'
# autoshift.io/coo-channel: 'stable'
# autoshift.io/coo-version: 'cluster-observability-operator.v1.x.x'