# Default values for devspaces.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
policy_namespace: open-cluster-policies
devspaces:
    name: devspaces
    namespace: openshift-operators-redhat
    channel: stable
    source: redhat-operators
    sourceNamespace: openshift-marketplace
# hubClusterSets:
#   hub:
#     labels:
#       test1: 'test'
# managedClusterSets:
#   managed:
#     labels:
#       test4: 'test'

### AutoShift Labels Documentation
# The following labels can be set at the cluster or clusterset level to configure this policy:
#
# Enable/Disable:
# dev-spaces<bool>: 'true' or 'false' - Enable OpenShift Dev Spaces (Eclipse Che)
#
# Configuration:
# dev-spaces-channel<String>: Operator channel (default: 'stable')
# dev-spaces-version<String>: Specific operator version (CSV) to install (optional)
# dev-spaces-source<String>: Operator catalog source (default: 'redhat-operators')
# dev-spaces-source-namespace<String>: Catalog namespace (default: 'openshift-marketplace')
#
# Note: Provides cloud-based development environments based on Eclipse Che
# Enables developers to work in consistent, containerized workspaces
#
# Examples:
# autoshift.io/dev-spaces: 'true'
# autoshift.io/dev-spaces-channel: 'stable'
# autoshift.io/dev-spaces-version: 'devspaces.v3.x.x'