apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-metallb-quota-config
  namespace: {{ .Values.policy_namespace }}
  annotations:
    policy.open-cluster-management.io/standards: AutoShiftv2
    policy.open-cluster-management.io/categories: Kubernetes MetalLB Operator
    policy.open-cluster-management.io/controls: OpenShift Standard
spec:
  dependencies:
    - name: policy-metallb-operator-install
      namespace: {{ .Values.policy_namespace }}
      apiVersion: policy.open-cluster-management.io/v1
      compliance: Compliant
      kind: Policy
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-quota-config
        spec:
          remediationAction: enforce # will be overridden by remediationAction in parent policy
          severity: high
          object-templates:
            - complianceType: mustonlyhave
              objectDefinition:
                apiVersion: v1
                kind: ResourceQuota
                metadata:
                  name: metallb-quota
                  namespace: metallb-system
                spec:
                  hard:
                    cpu: '{{ "{{hub" }} index .ManagedClusterLabels "autoshift.io/metallb-quota-cpu" | default "{{ .Values.metallb.quota.cpu }}" {{ "hub}}" }}'
                    memory: '{{ "{{hub" }} index .ManagedClusterLabels "autoshift.io/metallb-quota-memory" | default "{{ .Values.metallb.quota.memory }}" {{ "hub}}" }}'
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: placement-policy-quota-config
  namespace: {{ .Values.policy_namespace }}
spec:
  clusterSets:
  {{- range $clusterSet, $value := $.Values.managedClusterSets }}
    - {{ $clusterSet }}
  {{- end }}
  {{- range $clusterSet, $value := $.Values.hubClusterSets }}
    - {{ $clusterSet }}
  {{- end }}
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: 'autoshift.io/metallb-quota'
              operator: In
              values:
              - 'true'
  tolerations:
    - key: cluster.open-cluster-management.io/unreachable
      operator: Exists
    - key: cluster.open-cluster-management.io/unavailable
      operator: Exists
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: placement-policy-quota-config
  namespace: {{ .Values.policy_namespace }}
placementRef:
  name: placement-policy-quota-config
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
subjects:
  - name: policy-metallb-quota-config
    apiGroup: policy.open-cluster-management.io
    kind: Policy
