# Default values for openshift-dns.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
policy_namespace: open-cluster-policies

### AutoShift Labels Documentation
# The following labels can be set at the cluster or clusterset level to configure this policy:
#
# Note: This policy does not use autoshift.io labels for conditional deployment
# It applies DNS tolerations to all clusters in the configured cluster sets
# The policy configures DNS pods to tolerate all node taints using 'operator: Exists'
#
# Policy Function:
# - Adds tolerations to OpenShift DNS operator to run on any node
# - Ensures DNS services can run on tainted nodes (e.g., infra, storage nodes)
# - Always applied when cluster is in a managed cluster set