# Default values for logging.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
policy_namespace: open-cluster-policies
nmstate:
    name: kubernetes-nmstate-operator
    namespace: openshift-nmstate
    channel: stable
    source: redhat-operators
    sourceNamespace: openshift-marketplace

### AutoShift Labels Documentation
# The following labels can be set at the cluster or clusterset level to configure this policy:
#
# Enable/Disable:
# nmstate<bool>: 'true' or 'false' - Enable Kubernetes NMState Operator for network configuration (default: 'false')
#
# Configuration:
# nmstate-channel<String>: Operator channel (default: 'stable')
# nmstate-version<String>: Specific operator version (CSV) to install (optional)
# nmstate-source<String>: Operator catalog source (default: 'redhat-operators')
# nmstate-source-namespace<String>: Catalog namespace (default: 'openshift-marketplace')
#
# Network Configuration:
# nmstate-nncp-<name><String>: Filename of NMState config in files/ directory
#                             Can be specified multiple times for multiple configs
#                             Must have unique suffixes (e.g., nmstate-nncp-bond1, nmstate-nncp-vlan2)
#
# Note: Declaratively configures Red Hat CoreOS network settings
# Common uses include bonds, VLANs, and bridges
# Configuration files must exist in the files/ directory
#
# Examples:
# autoshift.io/nmstate: 'true'
# autoshift.io/nmstate-nncp-bond1: 'example-1g-bond'
# autoshift.io/nmstate-nncp-vlan2: 'example-vlan-config'
