# This policy verifies the installation of the official & supported version of
# the NMState Operator on the managed clusters.
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-nmstate-operator-install
  namespace: {{ .Values.policy_namespace }}
  annotations:
    policy.open-cluster-management.io/standards: AutoShiftv2
    policy.open-cluster-management.io/categories: Kubernetes NMState Operator
    policy.open-cluster-management.io/controls: OpenShift Standard
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: nmstate-operator-ns
        spec:
          remediationAction: enforce # will be overridden by remediationAction in parent policy
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Namespace
                metadata:
                  name: {{ .Values.nmstate.namespace }}
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1beta1
        kind: OperatorPolicy
        metadata:
          name: install-operator-nmstate
        spec:
          remediationAction: enforce
          severity: high
          complianceType: musthave
          operatorGroup:
            name: {{ .Values.nmstate.namespace }}
            namespace: {{ .Values.nmstate.namespace }}
            targetNamespaces:
              - {{ .Values.nmstate.namespace }}
          subscription:
            name: '{{ "{{hub" }} index .ManagedClusterLabels "autoshift.io/nmstate-subscription-name" | default "{{ .Values.nmstate.name }}" {{ "hub}}" }}'
            namespace: {{ .Values.nmstate.namespace }}
            source: '{{ "{{hub" }} index .ManagedClusterLabels "autoshift.io/nmstate-source" | default "{{ .Values.nmstate.source }}" {{ "hub}}" }}'
            sourceNamespace: '{{ "{{hub" }} index .ManagedClusterLabels "autoshift.io/nmstate-source-namespace" | default "{{ .Values.nmstate.sourceNamespace }}" {{ "hub}}" }}'
            channel: '{{ "{{hub" }} index .ManagedClusterLabels "autoshift.io/nmstate-channel" | default "{{ .Values.nmstate.channel }}" {{ "hub}}" }}'
            startingCSV: '{{ "{{hub" }} index .ManagedClusterLabels "autoshift.io/nmstate-version" | default "" {{ "hub}}" }}'
            # Upgrade approval for subscription will be set based on if version is set not this flag
            # If version is set install plan is set to manual and only the version specified will be installed
          upgradeApproval: Automatic
          versions:
            - '{{ "{{hub" }} index .ManagedClusterLabels "autoshift.io/nmstate-version" | default "" {{ "hub}}" }}'
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: openshift-nmstate-status
        spec:
          remediationAction: inform # will be overridden by remediationAction in parent policy
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1alpha1
                kind: ClusterServiceVersion
                metadata:
                  namespace: {{ .Values.nmstate.namespace }}
                spec:
                  displayName: Kubernetes NMState Operator
                status:
                  phase: Succeeded # check the csv status to determine if operator is running or not
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: placement-policy-nmstate-operator-install
  namespace: {{ .Values.policy_namespace }}
spec:
  clusterSets:
  {{- range $clusterSet, $value := $.Values.managedClusterSets }}
    - {{ $clusterSet }}
  {{- end }}
  {{- range $clusterSet, $value := $.Values.hubClusterSets }}
    - {{ $clusterSet }}
  {{- end }}
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: 'autoshift.io/nmstate'
              operator: In
              values:
              - 'true'
  tolerations:
    - key: cluster.open-cluster-management.io/unreachable
      operator: Exists
    - key: cluster.open-cluster-management.io/unavailable
      operator: Exists
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: placement-policy-nmstate-operator-install
  namespace: {{ .Values.policy_namespace }}
placementRef:
  name: placement-policy-nmstate-operator-install
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
subjects:
  - name: policy-nmstate-operator-install
    apiGroup: policy.open-cluster-management.io
    kind: Policy
