# This policy verifies the installation of the official & supported version of
# the NMState object on the managed clusters.
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-nmstate
  namespace: {{ .Values.policy_namespace }}
  annotations:
    policy.open-cluster-management.io/standards: AutoShiftv2
    policy.open-cluster-management.io/categories: Kubernetes NMState Operator
    policy.open-cluster-management.io/controls: OpenShift Standard
spec:
  dependencies:
    - name: policy-nmstate-operator-install
      namespace: {{ .Values.policy_namespace }}
      apiVersion: policy.open-cluster-management.io/v1
      compliance: Compliant
      kind: Policy
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: nmstate-operator-nmstate
        spec:
          remediationAction: enforce # will be overridden by remediationAction in parent policy
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: nmstate.io/v1
                kind: NMState
                metadata:
                  name: nmstate
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: nmstate-operator-nmstate-test
        spec:
          remediationAction: inform
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                kind: Deployment
                apiVersion: apps/v1
                metadata:
                  name: nmstate-webhook
                  namespace: {{ .Values.nmstate.namespace }}
                status:
                  conditions:
                    - type: Available
                      status: 'True'
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: placement-policy-nmstate
  namespace: {{ .Values.policy_namespace }}
spec:
  clusterSets:
  {{- range $clusterSet, $value := $.Values.managedClusterSets }}
    - {{ $clusterSet }}
  {{- end }}
  {{- range $clusterSet, $value := $.Values.hubClusterSets }}
    - {{ $clusterSet }}
  {{- end }}
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: 'autoshift.io/nmstate'
              operator: In
              values:
              - 'true'
  tolerations:
    - key: cluster.open-cluster-management.io/unreachable
      operator: Exists
    - key: cluster.open-cluster-management.io/unavailable
      operator: Exists
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: placement-policy-nmstate
  namespace: {{ .Values.policy_namespace }}
placementRef:
  name: placement-policy-nmstate
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
subjects:
  - name: policy-nmstate
    apiGroup: policy.open-cluster-management.io
    kind: Policy
