# Default values for storage-nodes.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
policy_namespace: open-cluster-policies
localStorage:
  name: local-storage-operator
  namespace: openshift-local-storage
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  channel: stable
# hubClusterSets:
#   hub:
#     labels:
#       test1: 'test'
# managedClusterSets:
#   managed:
#     labels:
#       test4: 'test'


### AutoShift Labels Documentation
# The following labels can be set at the cluster or clusterset level to configure this policy:
#
# Enable/Disable:
# local-storage<bool>: 'true' or 'false' - Enable Local Storage Operator
#
# Configuration:
# local-storage-channel<String>: Operator channel (default: 'stable')
# local-storage-version<String>: Specific operator version (CSV) to install (optional)
# local-storage-source<String>: Operator catalog source (default: 'redhat-operators')
# local-storage-source-namespace<String>: Catalog namespace (default: 'openshift-marketplace')
#
# Note: Automatically installed when storage nodes are enabled
#
# Examples:
# autoshift.io/local-storage: 'true'
# autoshift.io/local-storage-channel: 'stable'
# autoshift.io/local-storage-version: 'local-storage-operator.v4.x.x'