# Default values for rhtas-operator.
policy_namespace: open-cluster-policies
rhtasOperator:
  name: rhtas-operator
  namespace: openshift-operators
  channel: stable
  source: redhat-operators
  sourceNamespace: openshift-marketplace
# hubClusterSets:
#   hub:
#     labels:
#       test1: 'test'
# managedClusterSets:
#   managed:
#     labels:
#       test4: 'test'

### AutoShift Labels Documentation
# The following labels can be set at the cluster or clusterset level to configure this policy:
#
# Enable/Disable:
# tas<bool>: 'true' or 'false' - Enable Trusted Artifact Signer (RHTAS)
#
# Configuration:
# tas-channel<String>: Operator channel (default: 'stable')
# tas-version<String>: Specific operator version (CSV) to install (optional)
# tas-source<String>: Operator catalog source (default: 'redhat-operators')
# tas-source-namespace<String>: Catalog namespace (default: 'openshift-marketplace')
#
# Examples:
# autoshift.io/tas: 'true'
# autoshift.io/tas-channel: 'stable'
# autoshift.io/tas-version: 'rhtas-operator.v1.x.x'