# Default values for rh-acm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
policy_namespace: open-cluster-policies
acm: 
  namespace: open-cluster-management
  channel: release-2.14
  sourceNamespace: openshift-marketplace
  source: redhat-operators
  name: advanced-cluster-management
  disable_hub_self_management: false
  availabilityConfig: High
  enable_backup: false
  gitops_namespace: openshift-gitops
# hubClusterSets:
#   hub:
#     labels:
#       test1: 'test'
# managedClusterSets:
#   sandbox:
#     labels:
#       test3: 'test'
#   managed:
#     labels:
#       test4: 'test'

### AutoShift Labels Documentation
# The following labels can be set at the cluster or clusterset level to configure this policy:
#
# Core Configuration:
# self-managed<bool>: 'true' or 'false' - Controls self-management of hub cluster (default: 'true')
# acm-channel<String>: ACM operator channel (default: 'release-2.14')
# acm-version<String>: Specific operator version (CSV) to install (optional)
# acm-source<String>: Operator catalog source (default: 'redhat-operators')
# acm-source-namespace<String>: Catalog namespace (default: 'openshift-marketplace')
# acm-availability-config<String>: 'Basic' or 'High' - Availability configuration (default: 'High')
#
# Observability:
# acm-observability<bool>: 'true' or 'false' - Enable ACM observability (requires ODF)
#
# Examples:
# autoshift.io/self-managed: 'true'
# autoshift.io/acm-channel: 'release-2.14'
# autoshift.io/acm-version: 'advanced-cluster-management.v2.14.x'
# autoshift.io/acm-availability-config: 'High'
# autoshift.io/acm-observability: 'true'