# Default values for logging.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
policy_namespace: open-cluster-policies
logging:
    name: cluster-logging
    namespace: openshift-logging
    channel: stable-6.2
    source: redhat-operators
    sourceNamespace: openshift-marketplace
# hubClusterSets:
#   hub:
#     labels:
#       test1: 'test'
# managedClusterSets:
#   managed:
#     labels:
#       test4: 'test'

### AutoShift Labels Documentation
# The following labels can be set at the cluster or clusterset level to configure this policy:
#
# Enable/Disable:
# logging<bool>: 'true' or 'false' - Enable OpenShift Logging (depends on Loki and COO)
#
# Configuration:
# logging-channel<String>: Operator channel (default: 'stable-6.2')
# logging-version<String>: Specific operator version (CSV) to install (optional)
# logging-source<String>: Operator catalog source (default: 'redhat-operators')
# logging-source-namespace<String>: Catalog namespace (default: 'openshift-marketplace')
#
# Dependencies:
# - Requires Loki for log storage
# - Requires Cluster Observability Operator (COO)
#
# Examples:
# autoshift.io/logging: 'true'
# autoshift.io/logging-channel: 'stable-6.2'
# autoshift.io/logging-version: 'cluster-logging.v6.x.x'
