---
autoshiftGitRepo: https://github.com/auto-shift/autoshiftv2.git
autoshiftGitBranchTag: main

selfManagedHubSet: hub

# Optional: If you want to exclude policies from all clusters, you can add the folder name here.
# excludePolicies:
#   - infra-nodes
#   - worker-nodes


# Hub Cluster Sets with Feature Flags. Blank will remove
hubClusterSets:
  hub:
    labels:
      self-managed: 'true'
      ### Advance Cluster Manager
      acm-channel: release-2.14
      acm-source: redhat-operators
      acm-source-namespace: openshift-marketplace
      acm-availability-config: 'High'
      acm-observability: 'true'
      ### OpenShift Gitops
      gitops: 'true' # is expected to be installed on all hub clusters
      gitops-channel: latest
      gitops-source: redhat-operators
      gitops-source-namespace: openshift-marketplace
      ### MetalLB
      metallb: 'true'
      metallb-source: redhat-operators
      metallb-source-namespace: openshift-marketplace
      metallb-channel: stable
      # Specify the names of your IPPool files here
      metallb-ippool-1: ''
      #Specify your L2 Advertisement files here
      metallb-l2-1: ''
      # Specify the names of your BGP Advertisement files here
      metallb-bgp-1: ''
      # Specify the names of your Peer files here
      metallb-peer-1: ''
      ### Master Nodes
      master-nodes: 'false'
      master-max-pods: 500
      ### Infrastructure Nodes
      infra-nodes: ''
      infra-nodes-numcpu: ''
      infra-nodes-memory-mib: ''
      infra-nodes-numcores-per-socket: ''
      infra-nodes-zone-1: ''
      ### Worker Nodes
      worker-nodes: ''
      worker-nodes-numcpu: ''
      worker-nodes-memory-mib: ''
      worker-nodes-numcores-per-socket: ''
      worker-nodes-zone-1: ''
      ### Storage Nodes
      storage-nodes: '3'
      # storage-nodes-zone-1: 'us-east-2a'
      # storage-nodes-zone-2: 'us-east-2b'
      # storage-nodes-zone-3: 'us-east-2c'
      # storage-nodes-region: 'us-east-2'
      storage-nodes-provider: baremetal
      # storage-nodes-node-[iterator]: node-1 # For use with baremetal
      # storage-nodes-node-[iterator]: node-2 # For use with baremetal
      storage-nodes-numcpu: ''
      storage-nodes-memory-mib: ''
      storage-nodes-numcores-per-socket: ''
      ### LVM Operator
      lvm: 'false'
      lvm-default: 'true'
      lvm-fstype: xfs
      lvm-size-percent: 90
      lvm-overprovision-ratio: 10
      lvm-channel: stable-4.18
      lvm-source: redhat-operators
      lvm-source-namespace: openshift-marketplace
      ### Local Storage Operator
      local-storage: 'true'
      local-storage-channel: stable
      local-storage-source: redhat-operators
      local-storage-source-namespace: openshift-marketplace
      ### OpenShift Data Foundation
      odf: 'false'
      odf-multi-cloud-gateway: standard
      odf-nooba-pvpool: ''
      odf-nooba-store-size: ''
      odf-nooba-store-num-volumes: ''
      odf-ocs-storage-class-name: ''
      odf-ocs-storage-size: ''
      odf-ocs-storage-count: '3'
      odf-ocs-storage-replicas: '1' # Flexible Scaling uses replica 1 and count is the total of all your drives/OSDs
      odf-ocs-flexible-scaling: 'true'
      odf-resource-profile: 'lean'
      odf-channel: stable-4.18
      odf-source: redhat-operators
      odf-source-namespace: openshift-marketplace
      ### Kubernetes NMState Operator
      nmstate: 'true'
      # Example nmstate-nncp labels. Label must start with nmstate-nncp
      # also the value must be the name of the config file you want to apply
      # nmstate-nncp-example-bond1: example-bond
      # nmstate-nncp-example-vlan10: example-vlan10
      ### Advanced Cluster Security
      acs: 'true'
      acs-egress-connectivity: 'Offline'
      acs-channel: stable
      acs-source: redhat-operators
      acs-source-namespace: openshift-marketplace
      ### Developer Spaces
      dev-spaces: 'true'
      dev-spaces-channel: stable
      dev-spaces-source: redhat-operators
      dev-spaces-source-namespace: openshift-marketplace
      ### Developer Hub
      dev-hub: 'false'
      dev-hub-channel: fast
      dev-hub-source: redhat-operators
      dev-hub-source-namespace: openshift-marketplace
      ### OpenShift Pipelines
      pipelines: 'false'
      pipelines-channel: latest
      pipelines-source: redhat-operators
      pipelines-source-namespace: openshift-marketplace
      ### Trusted Artifact Signer
      tas: 'false'
      tas-channel:  stable
      tas-source: redhat-operators
      tas-source-namespace: openshift-marketplace
      ### Quay
      quay: 'false'
      quay-channel: stable-3.13
      quay-source: redhat-operators
      quay-source-namespace: openshift-marketplace
      ### Developer OpenShift Gitops
      gitops-dev: 'false'
      gitops-dev-team-test: 'hub' #hub or standalone
      # gitops-dev-team-{INSERT_TEAM_NAME}
      ### Loki
      loki: 'false'
      loki-channel: stable-6.2
      loki-source: redhat-operators
      loki-source-namespace: openshift-marketplace
      loki-size: 1x.extra-small
      loki-storageclass: lvms-vg1
      loki-lokistack-name: logging-lokistack
      ### OpenShift Logging
      logging: 'false'
      logging-channel:  stable-6.2
      logging-source: redhat-operators
      logging-source-namespace: openshift-marketplace
      ### Cluster Observability Operator
      coo: 'false'
      coo-channel: stable
      coo-source: redhat-operators
      coo-source-namespace: openshift-marketplace
      ### Compliance Operator Stig Apply
      compliance: 'false'
      compliance-name: compliance-operator
      compliance-source: redhat-operators
      compliance-source-namespace: openshift-marketplace
      compliance-channel: stable
      aap: true
      aap-channel: stable-2.6
      aap-file_storage_storage_class: nfs-csi
      aap-file_storage_size: 40G
      aap-s3-storage: false
      aap-eda-disabled: false
      aap-lightspeed-disabled: true
