# Default values for quay.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
policy_namespace: open-cluster-policies
quay:
    name: quay-operator
    cliImage: image-registry.openshift-image-registry.svc:5000/openshift/cli:latest
    namespace: quay-operator
    channel: stable-3.13
    source: redhat-operators
    sourceNamespace: openshift-marketplace
    enterpriseNamespace: quay-enterprise
    registry_config_bundle:
      FEATURE_USER_INITIALIZE: true
      BROWSER_API_CALLS_XHR_ONLY: false
      SUPER_USERS:
      - quayadmin
      FEATURE_USER_CREATION: false
    registry_components:
      - kind: clair
        managed: true
      - kind: postgres
        managed: true
      - kind: objectstorage
        managed: true
      - kind: redis
        managed: true
      - kind: horizontalpodautoscaler
        managed: true
      - kind: route
        managed: true
      - kind: mirror
        managed: true
      - kind: monitoring
        managed: true
      - kind: tls
        managed: true
      - kind: quay
        managed: true
      - kind: clairpostgres
        managed: true

# hubClusterSets:
#   hub:
#     labels:
#       test1: 'test'
# managedClusterSets:
#   managed:
#     labels:
#       test4: 'test'

### AutoShift Labels Documentation
# The following labels can be set at the cluster or clusterset level to configure this policy:
#
# Enable/Disable:
# quay<bool>: 'true' or 'false' - Enable Quay enterprise container registry
#
# Configuration:
# quay-channel<String>: Operator channel (default: 'stable-3.13')
# quay-version<String>: Specific operator version (CSV) to install (optional)
# quay-source<String>: Operator catalog source (default: 'redhat-operators')
# quay-source-namespace<String>: Catalog namespace (default: 'openshift-marketplace')
#
# Note: Quay automatically configures with managed components including:
# - PostgreSQL database
# - Object storage
# - Clair security scanning
# - Redis cache
# - Monitoring and TLS
#
# Examples:
# autoshift.io/quay: 'true'
# autoshift.io/quay-channel: 'stable-3.13'
# autoshift.io/quay-version: 'quay-operator.v3.x.x'