# Default values for infra-nodes.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
policy_namespace: open-cluster-policies
infraNodes:
  labelPrefix: "autoshift.io/"
  remediationAction: "enforce"
  imageRegistry: 
    migrate: true
    remediationAction: enforce
  ingress: 
    migrate: true
    remediationAction: enforce
  monitoring: 
    migrate: true
    remediationAction: enforce
  gitops: 
    migrate: true
    remediationAction: enforce
    namespace: openshift-gitops
    apiVersion: pipelines.openshift.io/v1alpha1
    kind: GitopsService
    metadata:
      name: cluster
  dependencies: 
    install: 
      - "policy-infra-nodes-test"
    remove: 
      - policy-remove-infra-gitops 
      - policy-remove-infra-image-registry
      - policy-remove-infra-ingress
      - policy-remove-infra-monitoring 

### AutoShift Labels Documentation
# The following labels can be set at the cluster or clusterset level to configure this policy:
#
# Enable/Disable:
# infra-nodes<Int>: Number of infrastructure nodes (if not set, infra nodes are not managed; if 0, infra nodes will be deleted)
#
# Provider Configuration:
# infra-nodes-provider<String>: Provider type - 'aws', 'vmware', or 'test'
#
# AWS Configuration:
# infra-nodes-instance-type<String>: AWS instance type
# infra-nodes-zone-[number]<String>: Availability zone (e.g., infra-nodes-zone-1: 'us-east-2a')
#
# VMware Configuration:
# infra-nodes-numcpu<Int>: Number of CPUs per infra node
# infra-nodes-memory-mib<Int>: Memory in MiB per infra node
# infra-nodes-numcores-per-socket<Int>: Number of CPU cores per socket
# infra-nodes-zone-[number]<String>: Availability zone
#
# Note: Infrastructure nodes are dedicated nodes that run platform services including:
# - OpenShift GitOps
# - Image Registry
# - Ingress Controllers
# - Monitoring stack
# This separates platform workloads from user application workloads
#
# Examples:
# autoshift.io/infra-nodes: '3'
# autoshift.io/infra-nodes-provider: 'aws'
# autoshift.io/infra-nodes-instance-type: 'm5.xlarge'
# autoshift.io/infra-nodes-zone-1: 'us-east-2a'
# autoshift.io/infra-nodes-zone-2: 'us-east-2b'
# autoshift.io/infra-nodes-zone-3: 'us-east-2c'
