# Default values for image registry
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
policy_namespace: open-cluster-policies
imageregistry: 
  clusterSets:
# hubClusterSets:
#   hub:
#     labels:
#       test1: 'test'
# managedClusterSets:
#   managed:
#     labels:
#       test4: 'test'

### AutoShift Labels Documentation
# The following labels can be set at the cluster or clusterset level to configure this policy:
#
# Enable/Disable:
# imageregistry<bool>: 'true' or 'false' - Enable OpenShift image registry configuration (default: 'false')
#
# Registry Configuration:
# imageregistry-management-state<String>: 'Managed' or 'Removed' (default: 'Managed')
# imageregistry-replicas<Int>: Number of registry replicas (default: 1)
# imageregistry-rollout-strategy<String>: 'Recreate' or 'RollingUpdate' (default: 'Recreate')
#
# Storage Configuration:
# imageregistry-storage-type<String>: 's3' or 'pvc' - Storage backend type
#
# S3 Storage Options:
# imageregistry-s3-region<String>: AWS region for S3 storage (default: 'us-east-1')
#
# PVC Storage Options:
# imageregistry-pvc-access-mode<String>: 'ReadWriteOnce' or 'ReadWriteMany'
# imageregistry-pvc-storage<String>: PVC size (default: '100Gi')
# imageregistry-pvc-storage-class<String>: Storage class name (e.g., 'ocs-storagecluster-ceph-rbd', 'gp3')
# imageregistry-pvc-volume-mode<String>: 'Block' or 'Filesystem' (default: 'Filesystem')
#
# Note: For replicas > 1, must use ReadWriteMany access mode or S3 storage
# S3 storage automatically uses NooBaa from OpenShift Data Foundation
#
# Examples:
# autoshift.io/imageregistry: 'true'
# autoshift.io/imageregistry-storage-type: 'pvc'
# autoshift.io/imageregistry-pvc-storage-class: 'ocs-storagecluster-ceph-rbd'
# autoshift.io/imageregistry-pvc-access-mode: 'ReadWriteMany'
