{{- range $clusterSet, $value := .Values.managedClusterSets }}
---
apiVersion: cluster.open-cluster-management.io/v1beta2
kind: ManagedClusterSet
metadata:
  name: {{ $clusterSet }}
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "5"
spec:
  clusterSelector:
    selectorType: ExclusiveClusterSetLabel
{{- end }}
{{- range $clusterSet, $value := .Values.hubClusterSets }}
---
apiVersion: cluster.open-cluster-management.io/v1beta2
kind: ManagedClusterSet
metadata:
  name: {{ $clusterSet }}
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "5"
spec:
  clusterSelector:
    selectorType: ExclusiveClusterSetLabel
{{- end }}