# Default values for compliance operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
policy_namespace: open-cluster-policies
compliance:
    name: compliance-operator
    namespace: openshift-compliance
    source: redhat-operators
    sourceNamespace: openshift-marketplace
    nameSub: compliance-operator
    channel: stable
# hubClusterSets:
#   hub:
#     labels:
#       test1: 'test'
# managedClusterSets:
#   managed:
#     labels:
#       test4: 'test'

### AutoShift Labels Documentation
# The following labels can be set at the cluster or clusterset level to configure this policy:
#
# Enable/Disable:
# compliance<bool>: 'true' or 'false' - Enable Compliance Operator (requires STIG profile config)
#
# Configuration:
# compliance-channel<String>: Operator channel (default: 'stable')
# compliance-version<String>: Specific operator version (CSV) to install (optional)
# compliance-source<String>: Operator catalog source (default: 'redhat-operators')
# compliance-source-namespace<String>: Catalog namespace (default: 'openshift-marketplace')
#
# Note: STIG profiles and remediations must be configured in the helm chart config map
#
# Examples:
# autoshift.io/compliance: 'true'
# autoshift.io/compliance-channel: 'stable'
# autoshift.io/compliance-version: 'compliance-operator.v1.x.x'