# Default values for odf-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
policy_namespace: open-cluster-policies
odf:
    name: odf-operator
    namespace: openshift-storage
    channel: stable-4.17
    source: redhat-operators
    sourceNamespace: openshift-marketplace
    noobaStoreSize: 500Gi
    noobaStoreNumVolumes: 1
    ocsStorageClassName: gp3-csi
    ocsStorageSize: 2Ti
    ocsStorageCount: 1
    ocsStorageReplicas: 3
    resourceProfile: balanced # lean: suitable for clusters with limited resources, balanced: suitable for most use cases, performance: suitable for clusters with high amount of resources.
# hubClusterSets:
#   hub:
#     labels:
#       test1: 'test'
# managedClusterSets:
#   managed:
#     labels:
#       test4: 'test'

### AutoShift Labels Documentation
# The following labels can be set at the cluster or clusterset level to configure this policy:
#
# Enable/Disable:
# odf<bool>: 'true' or 'false' - Enable OpenShift Data Foundation (if storage nodes enabled, deploys on local storage)
#
# Configuration:
# odf-channel<String>: Operator channel (default: 'stable-4.17')
# odf-version<String>: Specific operator version (CSV) to install (optional)
# odf-source<String>: Operator catalog source (default: 'redhat-operators')
# odf-source-namespace<String>: Catalog namespace (default: 'openshift-marketplace')
#
# Storage Mode:
# odf-multi-cloud-gateway<String>: 'standalone' or 'standard' - Standalone installs only NooBaa, standard installs full ODF
#
# NooBaa Configuration:
# odf-nooba-pvpool<bool>: 'true' - Use PV pool for storage (not recommended for cloud providers)
# odf-nooba-store-size<String>: Size of NooBaa backing store when using PV pool (default: '500Gi')
# odf-nooba-store-num-volumes<String>: Number of volumes for PV pool (default: '1')
#
# OCS Storage Configuration:
# odf-ocs-flexible-scaling<Bool>: Enables flexible scaling (default: 'false', except baremetal non multiple of 3 default: 'true')
# odf-ocs-storage-class-name<String>: Storage class for OCS if not using local-storage (default: 'gp3-csi')
# odf-ocs-storage-size<String>: Storage size per device (default: '2Ti')
# odf-ocs-storage-count<String>: Number of storage device sets (default: '1')
# odf-ocs-storage-replicas<String>: Number of replicas (default: '3')
#
# Performance:
# odf-resource-profile<String>: Resource profile - 'lean', 'balanced', or 'performance' (default: 'balanced')
#
# Examples:
# autoshift.io/odf: 'true'
# autoshift.io/odf-multi-cloud-gateway: 'standard'
# autoshift.io/odf-ocs-storage-size: '2Ti'
# autoshift.io/odf-resource-profile: 'balanced'