# Default values for rh-acm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
policy_namespace: open-cluster-policies
aap:
  namespace: ansible-automation-platform
  channel: 'stable-2.6'
  installPlanApproval: Automatic
  name: ansible-automation-platform-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  storageClass: ocs-storagecluster-cephfs
  storageType: file
  instanceName: aap
  redisMode: standalone
  image: quay.io/openshift/origin-cli:latest

# this is for argo type deployments of this chart (set to true)
ignoreHelmHooks: false
