apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-aap-instance
  namespace: {{ .Values.policy_namespace }}
  annotations:
    policy.open-cluster-management.io/standards: AutoShiftv2
    policy.open-cluster-management.io/categories: Kubernetes MetalLB Operator
    policy.open-cluster-management.io/controls: OpenShift Standard
spec:
  disabled: false
  dependencies:
    - name: policy-aap-operator-install
      namespace: {{ .Values.policy_namespace }}
      apiVersion: policy.open-cluster-management.io/v1
      compliance: Compliant
      kind: Policy
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: aap-instance
          namespace: policies-autoshift
        spec:
          remediationAction: enforce # will be overridden by remediationAction in parent policy
          severity: high
          object-templates-raw: |
            - complianceType: mustonlyhave
              objectDefinition:
                apiVersion: aap.ansible.com/v1alpha1
                kind: AnsibleAutomationPlatform
                metadata:
                  name: "{{ .Values.aap.instanceName }}"
                  namespace: "{{ .Values.aap.namespace }}"
                spec:
                  controller:
                    disabled: false
                  hub:
                    disabled: {{ "{{" }}hub index .ManagedClusterLabels "autoshift.io/aap-hub-disabled" | default "false" hub{{ "}}" }}
                    {{ "{{" }}hub- if eq (index .ManagedClusterLabels "autoshift.io/aap-file-storage" | default "false") "true" hub{{ "}}" }}
                    storage_type: '{{ "{{" }}hub index .ManagedClusterLabels "autoshift.io/aap-storage-type" | default "{{ .Values.aap.storageType }}" hub{{ "}}" }}'
                    file_storage_size: 10Gi
                    file_storage_storage_class: '{{ "{{" }}hub index .ManagedClusterLabels "autoshift.io/aap-file_storage_storage_class" | default "{{ .Values.aap.storageClass }}" hub{{ "}}" }}'
                    {{ "{{" }}hub- end hub{{ "}}" }}
                    {{ "{{" }}hub- if eq (index .ManagedClusterLabels "autoshift.io/aap-s3-storage" | default "false") "true" hub{{ "}}" }}
                    storage_type: S3
                    object_storage_s3_secret:  '{{ "{{" }}hub index .ManagedClusterLabels "autoshift.io/aap-hub-s3-secret-name" | default "s3-aap-odf" hub{{ "}}" }}'
                    {{ "{{" }}hub- end hub{{ "}}" }}
                  eda:
                    disabled: {{ "{{" }}hub index .ManagedClusterLabels "autoshift.io/aap-eda-disabled" | default "true" hub{{ "}}" }}
                  lightspeed:
                    disabled: {{ "{{" }}hub index .ManagedClusterLabels "autoshift.io/aap-lightspeed-disabled" | default "true" hub{{ "}}" }}
                  redis_mode: standalone
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: placement-policy-aap-instance
  namespace: {{ .Values.policy_namespace }}
spec:
  clusterSets:
  {{- range $clusterSet, $value := $.Values.hubClusterSets }}
    - {{ $clusterSet }}
  {{- end }}
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: 'autoshift.io/aap'
              operator: In
              values:
              - 'true'
  tolerations:
    - key: cluster.open-cluster-management.io/unreachable
      operator: Exists
    - key: cluster.open-cluster-management.io/unavailable
      operator: Exists
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: placement-policy-aap-instance
  namespace: {{ .Values.policy_namespace }}
placementRef:
  name: placement-policy-aap-instance
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
subjects:
  - name: policy-aap-instance
    apiGroup: policy.open-cluster-management.io
    kind: Policy
